apiVersion: kro.run/v1alpha1
kind: MCP
metadata:
  name: golden-shark-342
  namespace: hackman-hackathon
spec:
  name: golden-shark-342
  image: govindup63/plane:2075ffa23f508bdb239b09eb29f85fa3f44ec572
  replicas: 1
  namespace: hackman-hackathon
  containerPort: 8080
  ingress:
    enabled: true
    url: golden-shark-342.ghstmail.me
    path: /
    pathType: Prefix
