apiVersion: kro.run/v1alpha1
kind: MCP
metadata:
  name: crimson-griffin-169
  namespace: hackman-hackathon
spec:
  name: crimson-griffin-169
  image: govindup63/plane:15a58db1af25c5be488d87a41a091801010b450b
  replicas: 1
  namespace: hackman-hackathon
  containerPort: 8080
  ingress:
    enabled: true
    url: crimson-griffin-169.ghstmail.me
    path: /
    pathType: Prefix
